name: Check pull-request

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: dev

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@latest
      
    - name: Install packages
      run: npm ci  

    - name: Run linter
      run: npm run lint

    - name: Run tests
      if: success()
      run: npm run test
